DnaToRna.o:
	gcc -c DnaToRna.c -o DnaToRna.o

DnaToRna: DnaToRna.o
	gcc DnaToRna.o -o DnaToRna

nucCountCpp:
	c++ DnaToRna.cpp -o DnaToRnaCpp

nucCountJava:
	javac DnaToRna.java

clean: 
	-rm -f DnaToRna.o
	-rm -f DnaToRna
	-rm -f DnaToRnaCpp
	-rm -f DnaToRna.class